Import('env', 'arch', 'common', 'cereal', 'messaging', 'NEOS')
if arch == "aarch64":
  if NEOS:
    env.Program('_sensord', 'sensors_neos.cc', LIBS=['hardware', common, cereal, messaging, 'capnp', 'zmq', 'kj'])
  else:
    env.Program('_sensord', 'sensors_qcom.cc', LIBS=['hardware', common, cereal, messaging, 'capnp', 'zmq', 'kj'])
  lenv = env.Clone()
  if not NEOS:
    lenv['LIBPATH'] += ['/system/vendor/lib64']
    lenv.Program('_gpsd', ['gpsd.cc'], LIBS=['hardware', common, 'diag', 'time_genoff', cereal, messaging, 'capnp', 'zmq', 'kj'])
else:
  sensors = [
    'sensors/file_sensor.cc',
    'sensors/i2c_sensor.cc',
    'sensors/light_sensor.cc',
    'sensors/bmx055_accel.cc',
    'sensors/bmx055_gyro.cc',
    'sensors/bmx055_magn.cc',
  ]
  env.Program('_sensord', ['sensors_qcom2.cc'] + sensors, LIBS=[common, cereal, messaging, 'capnp', 'zmq', 'kj'])
