Import('env', 'qt_env', 'arch', 'common', 'messaging', 'gpucommon', 'visionipc', 'cereal')

src = ['ui.cc', 'paint.cc', 'sidebar.cc', '#phonelibs/nanovg/nanovg.c']
libs = [common, 'zmq', 'czmq', 'capnp', 'kj', 'm', cereal, messaging, gpucommon, visionipc]


if qt_env is None:
  #libs += ['EGL', 'GLESv3', 'c++_shared', 'log', 'utils', 'gui', 'hardware', 'ui', 'CB', 'gsl', 'adreno_utils', 'OpenSLES', 'cutils', 'uuid', 'OpenCL', 'framebuffer2', 'windoww']
  libs += ['EGL', 'GLESv3', 'c++_shared', 'framebuffer2', 'windoww', 'log', 'utils', 'gui', 'cutils', 'uuid', 'OpenCL']
  forcelink = ['/system/lib64/liblzma.so']
  linkflags = ['-Wl,-rpath=/system/lib64,-rpath=/system/comma/usr/lib']

  src += ["android/ui.cc"]
  env.Program('_ui', src,
    FORCELINK=forcelink,
    LIBS=libs)

else:
  qt_libs = ["pthread"]

  if arch == "Darwin":
    qt_env["FRAMEWORKS"] += ["QtWidgets", "QtGui", "QtCore", "QtDBus", "QtMultimedia"]
  else:
    qt_libs += ["Qt5Widgets", "Qt5Gui", "Qt5Core", "Qt5DBus"]

  if arch == "larch64":
    qt_libs += ["GLESv2"]
  else:
    qt_libs += ["GL"]

  if arch == "aarch64":
    libs += ['EGL', 'GLESv3', 'framebuffer2', 'windoww', 'log', 'utils', 'gui', 'OpenSLES', 'cutils', 'uuid', 'OpenCL']
    forcelink = ['/system/lib64/liblzma.so']
    linkflags = ['-Wl,-rpath=/system/lib64,-rpath=/system/comma/usr/lib']

  qt_src = ["qt/ui.cc", "qt/window.cc", "qt/settings.cc"] + src
  qt_env.Program("_ui", qt_src, LINKFLAGS=linkflags, FORCELINK=forcelink, LIBS=qt_libs + libs)
